fn main() {
    tauri_build::build();
    if let Err(e) = generate_api_manifest() {
        println!("cargo:warning=Failed to generate API manifest: {}", e);
    }
}

fn generate_api_manifest() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let src_dir = std::path::Path::new(&manifest_dir).join("src");

    let lib_path = src_dir.join("lib.rs");
    let lib_content = std::fs::read_to_string(&lib_path)?;
    let command_names = extract_handler_commands(&lib_content);

    let commands_dir = src_dir.join("commands");
    let mut commands: Vec<(String, Vec<String>)> = Vec::new();
    let mut events: Vec<String> = Vec::new();

    for entry in std::fs::read_dir(&commands_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }

        let content = std::fs::read_to_string(&path)?;

        // Extract event emissions from this file
        for event in extract_events(&content) {
            if !events.contains(&event) {
                events.push(event);
            }
        }

        // For each known command, check if it's defined in this file
        for cmd_name in &command_names {
            if commands.iter().any(|(n, _)| *n == *cmd_name) {
                continue;
            }
            if let Some(params) = extract_command_fn(&content, cmd_name) {
                commands.push((cmd_name.clone(), params));
            }
        }
    }

    // Preserve the registration order from generate_handler!
    commands.sort_by(|a, b| {
        let ai = command_names.iter().position(|n| n == &a.0).unwrap_or(0);
        let bi = command_names.iter().position(|n| n == &b.0).unwrap_or(0);
        ai.cmp(&bi)
    });
    events.sort();

    // Build JSON
    let cmd_json: Vec<String> = commands
        .iter()
        .map(|(name, args)| {
            let args_json: Vec<String> = args.iter().map(|a| format!("\"{}\"", a)).collect();
            format!("{{\"name\":\"{}\",\"args\":[{}]}}", name, args_json.join(","))
        })
        .collect();

    let evt_json: Vec<String> = events.iter().map(|e| format!("{{\"name\":\"{}\"}}", e)).collect();

    let manifest = format!(
        "{{\"format\":1,\"commands\":[{}],\"events\":[{}]}}",
        cmd_json.join(","),
        evt_json.join(",")
    );

    let out_path = src_dir.join("generated_api_manifest.rs");
    std::fs::write(
        &out_path,
        format!(
            "// Generated by build.rs — do not edit manually\n\
             pub const API_MANIFEST_JSON: &str = r#\"{}\"#;\n",
            manifest
        ),
    )?;

    // Tell Cargo when to re-run
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/commands/");
    for entry in std::fs::read_dir(&commands_dir)? {
        let entry = entry?;
        if entry.path().extension().and_then(|e| e.to_str()) == Some("rs") {
            println!(
                "cargo:rerun-if-changed={}",
                entry.path().to_string_lossy()
            );
        }
    }

    Ok(())
}

/// Extract the list of command function names from `generate_handler![...]`.
fn extract_handler_commands(source: &str) -> Vec<String> {
    let marker = "generate_handler!";
    let start = match source.find(marker) {
        Some(s) => s + marker.len(),
        None => return vec![],
    };

    let bracket_start = match source[start..].find('[') {
        Some(s) => start + s + 1,
        None => return vec![],
    };

    let mut depth = 1u32;
    let mut i = bracket_start;
    let bytes = source.as_bytes();
    while depth > 0 && i < source.len() {
        match bytes[i] {
            b'[' => depth += 1,
            b']' => depth -= 1,
            _ => {}
        }
        i += 1;
    }
    if depth != 0 {
        return vec![];
    }

    source[bracket_start..i - 1]
        .split(',')
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .map(|s| s.strip_prefix("commands::").unwrap_or(s).to_string())
        .collect()
}

/// Extract a command function's parameter names (excluding Tauri-injected params).
fn extract_command_fn(source: &str, cmd_name: &str) -> Option<Vec<String>> {
    let search = format!("fn {}(", cmd_name);
    let start = source.find(&search)?;
    let paren_start = start + search.len();

    let mut depth = 1u32;
    let mut i = paren_start;
    let bytes = source.as_bytes();
    while depth > 0 && i < source.len() {
        match bytes[i] {
            b'(' | b'[' | b'{' => depth += 1,
            b')' | b']' | b'}' => depth -= 1,
            _ => {}
        }
        i += 1;
    }
    if depth != 0 {
        return None;
    }

    let params_str = &source[paren_start..i - 1];

    // Split by commas at depth 0 (handling nested generics)
    let mut params: Vec<String> = Vec::new();
    let mut pdepth = 0u32;
    let mut current = String::new();
    for ch in params_str.chars() {
        match ch {
            '<' | '(' | '[' | '{' => {
                pdepth += 1;
                current.push(ch);
            }
            '>' | ')' | ']' | '}' => {
                pdepth = pdepth.saturating_sub(1);
                current.push(ch);
            }
            ',' if pdepth == 0 => {
                let trimmed = current.trim().to_string();
                if !trimmed.is_empty() {
                    params.push(trimmed);
                }
                current = String::new();
            }
            _ => current.push(ch),
        }
    }
    let trimmed = current.trim().to_string();
    if !trimmed.is_empty() {
        params.push(trimmed);
    }

    // Filter out Tauri-injected params and convert names to camelCase
    let filtered: Vec<String> = params
        .iter()
        .filter_map(|p| {
            let colon = p.find(':')?;
            let raw_name = p[..colon].trim();
            let raw_type = p[colon + 1..].trim();

            if is_injected_type(raw_type) {
                return None;
            }

            let name = raw_name.strip_prefix("mut ").unwrap_or(raw_name);
            Some(snake_to_camel(name))
        })
        .collect();

    Some(filtered)
}

/// Check if a parameter type is injected by Tauri (not part of the API surface).
fn is_injected_type(ty: &str) -> bool {
    ty.starts_with("State<")
        || ty == "AppHandle"
        || ty.starts_with("tauri::AppHandle")
        || ty == "Window"
        || ty.starts_with("tauri::Window")
}

/// Convert snake_case to camelCase.
fn snake_to_camel(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut capitalize = false;
    for ch in s.chars() {
        if ch == '_' {
            capitalize = true;
        } else if capitalize {
            result.push(ch.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(ch);
        }
    }
    result
}

/// Extract event names from `.emit("name"` or `.emit(\n  "name"` calls.
fn extract_events(source: &str) -> Vec<String> {
    let mut events = Vec::new();
    let mut pos = 0;
    while let Some(start) = source[pos..].find(".emit(") {
        let after = pos + start + 6; // skip ".emit("
        if after >= source.len() {
            break;
        }

        // Skip whitespace (including newlines) before the event name
        let tail = &source[after..];
        let skip = tail.len() - tail.trim_start().len();
        let trimmed = &tail[skip..];
        let quote_char = match trimmed.chars().next() {
            Some(c) if c == '"' || c == '\'' => c,
            _ => {
                pos = after;
                continue;
            }
        };

        if let Some(end) = trimmed[1..].find(quote_char) {
            let name = &trimmed[1..=end];
            events.push(name.to_string());
            pos = after + skip + end + 2; // past closing quote
        } else {
            pos = after + 1;
        }
    }
    events
}
