import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'node:path'
import { COMMANDS, EVENTS } from './src/shared/api-definitions'

// ── Vite virtual module: frontend API manifest ──
// The manifest is computed from the central COMMANDS/EVENTS data structure
// so it always reflects what the frontend actually calls — no manual
// maintenance needed.  Compared at runtime against the backend manifest
// (auto-generated by build.rs from Rust #[tauri::command] functions) to
// detect when the two sides drift apart.

const VIRTUAL_MODULE_ID = 'virtual:api-manifest'
const RESOLVED_VIRTUAL_ID = '\0' + VIRTUAL_MODULE_ID

function apiManifestPlugin(): Plugin {
  const defsPath = path.resolve(__dirname, 'src/shared/api-definitions.ts')

  return {
    name: 'api-manifest',
    resolveId(id) {
      if (id === VIRTUAL_MODULE_ID) return RESOLVED_VIRTUAL_ID
    },
    load(id) {
      if (id !== RESOLVED_VIRTUAL_ID) return
      this.addWatchFile(defsPath)
      const manifest = {
        format: 1,
        commands: Object.values(COMMANDS).map((cmd) => ({ name: cmd.name, args: cmd.params })),
        events: Object.values(EVENTS).map((evt) => ({ name: evt.name })),
      }
      return `export const API_MANIFEST = ${JSON.stringify(manifest)};`
    },
    handleHotUpdate(ctx) {
      if (ctx.file === defsPath) {
        const mod = ctx.server.moduleGraph.getModuleById(RESOLVED_VIRTUAL_ID)
        if (mod) ctx.server.moduleGraph.invalidateModule(mod)
        ctx.server.ws.send({ type: 'full-reload', path: '*' })
      }
    },
  }
}

// ── Vite config ──

export default defineConfig({
  plugins: [react(), apiManifestPlugin()],
  root: 'src/renderer',
  base: './',
  clearScreen: false,
  server: {
    port: 20742,
    strictPort: false,
  },
  envPrefix: ['VITE_', 'TAURI_'],
  build: {
    target: process.env.TAURI_PLATFORM === 'windows' ? 'chrome105' : 'safari14',
    minify: !process.env.TAURI_DEBUG ? 'esbuild' : false,
    sourcemap: !!process.env.TAURI_DEBUG,
    outDir: path.resolve(__dirname, 'out/renderer'),
    emptyOutDir: true,
  },
})
